/*
 * Copyright 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jetlinks.reactor.mqtt.client;

import io.netty.handler.codec.mqtt.MqttQoS;
import org.jetlinks.reactor.mqtt.server.MqttServer;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.test.StepVerifier;

import java.time.Duration;

import static org.junit.jupiter.api.Assertions.*;

/**
 * MQTT 客户端测试
 *
 * @author PengyuDeng
 */
class MqttClientTest {

    private DisposableServer server;
    private ClientConnection client;
    private static final int TEST_PORT = 11884;

    @BeforeEach
    void setUp() {
        // 每个测试前启动服务端
        server = MqttServer.create()
                           .host("127.0.0.1")
                           .port(TEST_PORT)
                           .handle(connection -> connection.accept())
                           .bindNow();
    }

    @AfterEach
    void tearDown() {
        // 清理客户端连接
        if (client != null && client.isAlive()) {
            try {
                client.disconnect().block(Duration.ofSeconds(2));
            } catch (Exception e) {
                // 忽略断开连接时的异常
            }
        }

        // 清理服务端
        if (server != null && !server.isDisposed()) {
            server.disposeNow(Duration.ofSeconds(2));
        }
    }

    @Test
    @Timeout(10)
    void testClientConnectAndDisconnect() {
        // 测试客户端连接和断开
        StepVerifier.create(
                            MqttClient.create()
                                      .host("127.0.0.1")
                                      .port(TEST_PORT)
                                      .clientId("test-client")
                                      .connect()
                                      .doOnNext(conn -> client = conn)
                    )
                    .expectNextCount(1)
                    .verifyComplete();

        // 验证连接状态
        assertNotNull(client);
        assertTrue(client.isAlive());
        assertTrue(client.isConnected());

        // 断开连接
        StepVerifier.create(client.disconnect())
                    .verifyComplete();

        assertFalse(client.isAlive());
    }

    @Test
    @Timeout(10)
    void testClientConnectNow() {
        // 测试同步连接
        client = MqttClient.create()
                           .host("127.0.0.1")
                           .port(TEST_PORT)
                           .clientId("test-client-sync")
                           .connectNow();

        assertNotNull(client);
        assertTrue(client.isAlive());
        assertTrue(client.isConnected());
    }

    @Test
    @Timeout(10)
    void testClientWithCustomConfiguration() {
        // 测试自定义配置
        client = MqttClient.create()
                           .host("127.0.0.1")
                           .port(TEST_PORT)
                           .clientId("custom-client")
                           .keepAlive((short) 30)
                           .cleanSession(true)
                           .qos(MqttQoS.AT_LEAST_ONCE)
                           .connectTimeout(Duration.ofSeconds(5))
                           .connectNow();

        assertNotNull(client);
        assertTrue(client.isAlive());
        assertEquals(MqttQoS.AT_LEAST_ONCE, client.getQos());
    }

    @Test
    @Timeout(10)
    void testClientAutoGeneratedClientId() {
        // 测试自动生成客户端ID
        client = MqttClient.create()
                           .host("127.0.0.1")
                           .port(TEST_PORT)
                           // 不设置clientId，应该自动生成
                           .connectNow();

        assertNotNull(client);
        assertTrue(client.isAlive());
        assertNotNull(client.getClientId());
        assertTrue(client.getClientId().startsWith("reactor-mqtt-"));
    }

    @Test
    @Timeout(10)
    void testMultipleClients() {
        // 测试多个客户端连接
        ClientConnection client1 = MqttClient.create()
                                             .host("127.0.0.1")
                                             .port(TEST_PORT)
                                             .clientId("client-1")
                                             .connectNow();

        ClientConnection client2 = MqttClient.create()
                                             .host("127.0.0.1")
                                             .port(TEST_PORT)
                                             .clientId("client-2")
                                             .connectNow();

        try {
            assertNotNull(client1);
            assertNotNull(client2);
            assertTrue(client1.isAlive());
            assertTrue(client2.isAlive());
            assertNotEquals(client1.getClientId(), client2.getClientId());
        } finally {
            client1.disconnect().block(Duration.ofSeconds(2));
            client2.disconnect().block(Duration.ofSeconds(2));
        }
    }

    @Test
    @Timeout(10)
    void testClientOnCloseReactive() {
        Mono<Void> testFlow = MqttClient.create()
                                        .host("127.0.0.1")
                                        .port(TEST_PORT)
                                        .clientId("test-onclose")
                                        .connect()
                                        .flatMap(connection -> {
                                            Mono<Void> closeSignal = connection.onClose()
                                                                               .doOnTerminate(() -> System.out.println(">>> 连接已彻底关闭信号触发"));

                                            return connection.disconnect()
                                                             .doOnSuccess(v -> System.out.println(">>> 断开连接指令发送成功"))
                                                             .then(closeSignal); // 核心：确保流等待物理关闭信号
                                        });

        StepVerifier.create(testFlow)
                    .expectComplete()
                    .verify(Duration.ofSeconds(5));
    }

    @Test
    @Timeout(10)
    void testClientConnectionFailure() {
        // 测试连接失败（连接到不存在的服务器）
        StepVerifier.create(
                            MqttClient.create()
                                      .host("127.0.0.1")
                                      .port(19999) // 使用不存在的端口
                                      .clientId("test-fail")
                                      .connectTimeout(Duration.ofSeconds(2))
                                      .connect()
                    )
                    .expectError()
                    .verify();
    }

    @Test
    @Timeout(10)
    void testClientReconnectDisabled() {
        // 测试禁用重连
        client = MqttClient.create()
                           .host("127.0.0.1")
                           .port(TEST_PORT)
                           .clientId("test-no-reconnect")
                           .reconnect(false)
                           .connectNow();

        assertNotNull(client);
        assertTrue(client.isAlive());
    }

    @Test
    @Timeout(10)
    void testClientDefaultQoS() {
        // 测试默认QoS设置
        client = MqttClient.create()
                           .host("127.0.0.1")
                           .port(TEST_PORT)
                           .clientId("test-qos")
                           .qos(MqttQoS.EXACTLY_ONCE)
                           .connectNow();

        assertEquals(MqttQoS.EXACTLY_ONCE, client.getQos());
    }

    @Test
    @Timeout(10)
    void testClientWithAuthentication() {
        // 测试带认证的连接（服务端不验证，但测试客户端能否设置）
        client = MqttClient.create()
                           .host("127.0.0.1")
                           .port(TEST_PORT)
                           .clientId("test-auth")
                           .auth("username", "password")
                           .connectNow();

        assertNotNull(client);
        assertTrue(client.isAlive());
    }
}
